INSERT INTO student(firstName,lastName pin, dateOfBirth, indeks) VALUES ('Bolek','Puziolek' '90012345334', '1990-01-10')
INSERT INTO student(firstName,lastName pin, dateOfBirth, indeks) VALUES ('Lolek','Famfolek', '911002384775', '1991-10-02')
INSERT INTO student(firstName,lastName pin, dateOfBirth, indeks) VALUES('Tola', 'Patola', '92011024554', '1992-01-10')

INSERT INTO wydzial(nazwa, skrot) VALUES ('MatFizInf', 'MFI')
INSERT INTO wydzial(nazwa, skrot) VALUES('NaukSpolecznych', 'WNS')
INSERT INTO wydzial(nazwa, skrot) VALUES ('Filologia', 'Fil')
INSERT INTO wydzial(nazwa, skrot) VALUES ('Ekonomiczny', 'Ekon')
INSERT INTO wydzial(nazwa, skrot) VALUES ('GierIZabaw', 'ETI')
INSERT INTO wydzial(nazwa, skrot) VALUES ('Historyczny', 'His')